version: '3'

networks:
  laravel:

services:
  nginx:
    container_name: funil-nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: funil-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: funil
      MYSQL_DATABASE: funil
      MYSQL_USER: funil
      MYSQL_PASSWORD: funil
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: funil-php
    volumes:
      - ./src:/var/www
    ports:
      - "9000"
    networks:
      - laravel

